name: 'Test_terraform_module.yml'

on:
  push:
    branches: 
      -  main

env: 
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{vars.ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: test

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Terraform
      shell: pwsh
      run: |
            ls
            cd './terraform projects/modules/azurerm-vm-bundle/test 2/'
            terraform init
            terraform apply --auto-approve=true
           
